/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *home;
    QLabel *img;
    QPushButton *Sign;
    QLabel *text;
    QLineEdit *Pass;
    QLabel *Title;
    QPushButton *Login;
    QLineEdit *Phone;
    QWidget *signin;
    QLabel *img_2;
    QLabel *text_9;
    QLineEdit *Phone_4;
    QPushButton *Sign_4;
    QLineEdit *Pass_6;
    QPushButton *back_21;
    QWidget *menu;
    QLabel *img_3;
    QLabel *text_10;
    QPushButton *Logout_2;
    QPushButton *Cancel_2;
    QPushButton *Book_2;
    QPushButton *History_2;
    QWidget *spc;
    QLabel *img_4;
    QCommandLinkButton *sp_9;
    QCommandLinkButton *sp_10;
    QLabel *text_11;
    QCommandLinkButton *sp_4;
    QCommandLinkButton *sp_5;
    QCommandLinkButton *sp_11;
    QCommandLinkButton *sp_12;
    QPushButton *back;
    QWidget *slot;
    QLabel *img_5;
    QPushButton *book_2;
    QLabel *text_12;
    QPushButton *back_2;
    QLineEdit *pat_name;
    QLabel *text_2;
    QLineEdit *doc_name;
    QLineEdit *selected_slot;
    QLabel *text_3;
    QLabel *text_4;
    QLabel *text_5;
    QLineEdit *patient_age;
    QLineEdit *contact_no;
    QLabel *text_59;
    QLineEdit *a_pass;
    QLabel *text_64;
    QWidget *doctor;
    QLabel *img_6;
    QLabel *text_13;
    QRadioButton *doc_5;
    QPushButton *next_2;
    QRadioButton *doc_6;
    QPushButton *back_3;
    QWidget *det;
    QLabel *img_7;
    QCommandLinkButton *push_3;
    QCommandLinkButton *push_16;
    QLabel *img_16;
    QLabel *text_21;
    QCommandLinkButton *sl_2;
    QCommandLinkButton *sl_3;
    QCommandLinkButton *sl_5;
    QCommandLinkButton *sl_6;
    QCommandLinkButton *sl_7;
    QCommandLinkButton *sl;
    QCommandLinkButton *sl_4;
    QCommandLinkButton *sl_8;
    QWidget *det_2;
    QLabel *img_8;
    QCommandLinkButton *push_4;
    QCommandLinkButton *push_17;
    QLabel *img_17;
    QCommandLinkButton *sl_9;
    QLabel *text_22;
    QCommandLinkButton *sl_10;
    QCommandLinkButton *sl_11;
    QCommandLinkButton *sl_12;
    QCommandLinkButton *sl_13;
    QCommandLinkButton *sl_14;
    QCommandLinkButton *sl_15;
    QCommandLinkButton *sl_16;
    QWidget *doctor_7;
    QLabel *img_9;
    QRadioButton *doc_9;
    QRadioButton *doc_10;
    QLabel *text_15;
    QPushButton *next_4;
    QPushButton *back_4;
    QWidget *det_3;
    QLabel *img_23;
    QCommandLinkButton *push_7;
    QCommandLinkButton *push_18;
    QCommandLinkButton *sl_17;
    QCommandLinkButton *sl_18;
    QCommandLinkButton *sl_19;
    QCommandLinkButton *sl_20;
    QCommandLinkButton *sl_21;
    QCommandLinkButton *sl_22;
    QCommandLinkButton *sl_23;
    QLabel *text_23;
    QCommandLinkButton *sl_24;
    QLabel *img_18;
    QWidget *det_4;
    QLabel *img_24;
    QCommandLinkButton *push_8;
    QCommandLinkButton *push_19;
    QCommandLinkButton *sl_25;
    QCommandLinkButton *sl_26;
    QCommandLinkButton *sl_27;
    QCommandLinkButton *sl_28;
    QCommandLinkButton *sl_29;
    QCommandLinkButton *sl_30;
    QCommandLinkButton *sl_31;
    QLabel *text_24;
    QCommandLinkButton *sl_32;
    QLabel *img_19;
    QWidget *doctor_3;
    QLabel *img_10;
    QLabel *text_16;
    QRadioButton *doc_11;
    QRadioButton *doc_12;
    QPushButton *next_5;
    QPushButton *back_5;
    QWidget *det_5;
    QLabel *img_25;
    QCommandLinkButton *push_9;
    QCommandLinkButton *push_20;
    QCommandLinkButton *sl_33;
    QCommandLinkButton *sl_34;
    QCommandLinkButton *sl_35;
    QCommandLinkButton *sl_36;
    QCommandLinkButton *sl_37;
    QCommandLinkButton *sl_38;
    QCommandLinkButton *sl_39;
    QLabel *text_25;
    QCommandLinkButton *sl_40;
    QLabel *img_29;
    QWidget *det_6;
    QLabel *img_26;
    QCommandLinkButton *push_10;
    QCommandLinkButton *push_21;
    QCommandLinkButton *sl_41;
    QCommandLinkButton *sl_42;
    QCommandLinkButton *sl_43;
    QCommandLinkButton *sl_44;
    QCommandLinkButton *sl_45;
    QCommandLinkButton *sl_46;
    QCommandLinkButton *sl_47;
    QLabel *text_26;
    QCommandLinkButton *sl_48;
    QLabel *img_31;
    QWidget *doctor_4;
    QLabel *img_11;
    QLabel *text_17;
    QRadioButton *doc_13;
    QRadioButton *doc_14;
    QPushButton *next_6;
    QPushButton *back_6;
    QWidget *det_7;
    QLabel *img_27;
    QCommandLinkButton *push_11;
    QCommandLinkButton *push_22;
    QCommandLinkButton *sl_49;
    QCommandLinkButton *sl_50;
    QCommandLinkButton *sl_51;
    QCommandLinkButton *sl_52;
    QCommandLinkButton *sl_53;
    QCommandLinkButton *sl_54;
    QCommandLinkButton *sl_55;
    QLabel *text_27;
    QCommandLinkButton *sl_56;
    QLabel *img_32;
    QWidget *det_8;
    QLabel *img_28;
    QCommandLinkButton *push_12;
    QCommandLinkButton *push_23;
    QCommandLinkButton *sl_57;
    QCommandLinkButton *sl_58;
    QCommandLinkButton *sl_59;
    QCommandLinkButton *sl_60;
    QCommandLinkButton *sl_61;
    QCommandLinkButton *sl_62;
    QCommandLinkButton *sl_63;
    QLabel *text_28;
    QCommandLinkButton *sl_64;
    QLabel *img_33;
    QWidget *doctor_5;
    QLabel *img_12;
    QLabel *text_18;
    QRadioButton *doc_15;
    QRadioButton *doc_16;
    QPushButton *next_7;
    QPushButton *back_7;
    QWidget *det_9;
    QLabel *img_13;
    QCommandLinkButton *push_13;
    QCommandLinkButton *push_24;
    QCommandLinkButton *sl_65;
    QCommandLinkButton *sl_66;
    QCommandLinkButton *sl_67;
    QCommandLinkButton *sl_68;
    QCommandLinkButton *sl_69;
    QCommandLinkButton *sl_70;
    QCommandLinkButton *sl_71;
    QLabel *text_29;
    QCommandLinkButton *sl_72;
    QLabel *img_34;
    QWidget *det_10;
    QLabel *img_30;
    QCommandLinkButton *push_14;
    QCommandLinkButton *push_25;
    QCommandLinkButton *sl_73;
    QCommandLinkButton *sl_74;
    QCommandLinkButton *sl_75;
    QCommandLinkButton *sl_76;
    QCommandLinkButton *sl_77;
    QCommandLinkButton *sl_78;
    QCommandLinkButton *sl_79;
    QLabel *text_30;
    QCommandLinkButton *sl_80;
    QLabel *img_35;
    QWidget *doctor_2;
    QLabel *img_20;
    QRadioButton *doc;
    QRadioButton *doc_7;
    QLabel *text_14;
    QPushButton *next_3;
    QPushButton *back_8;
    QWidget *det_11;
    QLabel *img_21;
    QCommandLinkButton *push_5;
    QCommandLinkButton *push_26;
    QCommandLinkButton *sl_81;
    QCommandLinkButton *sl_82;
    QCommandLinkButton *sl_83;
    QCommandLinkButton *sl_84;
    QCommandLinkButton *sl_85;
    QCommandLinkButton *sl_86;
    QCommandLinkButton *sl_87;
    QLabel *text_31;
    QCommandLinkButton *sl_88;
    QLabel *img_36;
    QWidget *det_12;
    QLabel *img_22;
    QCommandLinkButton *push_6;
    QCommandLinkButton *push_27;
    QCommandLinkButton *sl_89;
    QCommandLinkButton *sl_90;
    QCommandLinkButton *sl_91;
    QCommandLinkButton *sl_92;
    QCommandLinkButton *sl_93;
    QCommandLinkButton *sl_94;
    QCommandLinkButton *sl_95;
    QLabel *text_32;
    QCommandLinkButton *sl_96;
    QLabel *img_37;
    QWidget *history;
    QLabel *img_14;
    QLabel *text_19;
    QPushButton *back_9;
    QTableView *tableView;
    QWidget *cancel;
    QLabel *img_15;
    QLabel *text_20;
    QPushButton *cancel_3;
    QLineEdit *c_doc;
    QLineEdit *c_slot;
    QLineEdit *c_pass;
    QLabel *text_61;
    QLabel *text_62;
    QLabel *text_63;
    QPushButton *back_10;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(700, 410);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 0, 700, 410));
        home = new QWidget();
        home->setObjectName("home");
        img = new QLabel(home);
        img->setObjectName("img");
        img->setGeometry(QRect(0, 0, 700, 400));
        img->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img.jpg")));
        img->setScaledContents(true);
        Sign = new QPushButton(home);
        Sign->setObjectName("Sign");
        Sign->setGeometry(QRect(180, 310, 80, 24));
        text = new QLabel(home);
        text->setObjectName("text");
        text->setGeometry(QRect(140, 280, 171, 16));
        QFont font;
        font.setPointSize(11);
        text->setFont(font);
        text->setStyleSheet(QString::fromUtf8("color: rgb(67, 69, 70);"));
        Pass = new QLineEdit(home);
        Pass->setObjectName("Pass");
        Pass->setGeometry(QRect(60, 180, 311, 41));
        Pass->setEchoMode(QLineEdit::Password);
        Title = new QLabel(home);
        Title->setObjectName("Title");
        Title->setGeometry(QRect(80, 0, 311, 131));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Bahnschrift SemiBold")});
        font1.setPointSize(48);
        font1.setBold(true);
        Title->setFont(font1);
        Title->setFocusPolicy(Qt::NoFocus);
        Title->setAcceptDrops(false);
        Title->setAutoFillBackground(false);
        Title->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        Title->setTextFormat(Qt::AutoText);
        Title->setScaledContents(false);
        Login = new QPushButton(home);
        Login->setObjectName("Login");
        Login->setGeometry(QRect(160, 240, 121, 31));
        Login->setFont(font);
        Login->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);"));
        Phone = new QLineEdit(home);
        Phone->setObjectName("Phone");
        Phone->setGeometry(QRect(60, 120, 311, 40));
        stackedWidget->addWidget(home);
        signin = new QWidget();
        signin->setObjectName("signin");
        img_2 = new QLabel(signin);
        img_2->setObjectName("img_2");
        img_2->setGeometry(QRect(0, 0, 700, 400));
        img_2->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img.jpg")));
        img_2->setScaledContents(true);
        text_9 = new QLabel(signin);
        text_9->setObjectName("text_9");
        text_9->setGeometry(QRect(140, 30, 201, 91));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Bahnschrift SemiBold")});
        font2.setPointSize(36);
        font2.setBold(true);
        text_9->setFont(font2);
        text_9->setFocusPolicy(Qt::NoFocus);
        text_9->setAcceptDrops(false);
        text_9->setAutoFillBackground(false);
        text_9->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_9->setTextFormat(Qt::AutoText);
        text_9->setScaledContents(false);
        Phone_4 = new QLineEdit(signin);
        Phone_4->setObjectName("Phone_4");
        Phone_4->setGeometry(QRect(70, 140, 311, 40));
        Sign_4 = new QPushButton(signin);
        Sign_4->setObjectName("Sign_4");
        Sign_4->setGeometry(QRect(170, 290, 121, 31));
        Sign_4->setFont(font);
        Sign_4->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);"));
        Pass_6 = new QLineEdit(signin);
        Pass_6->setObjectName("Pass_6");
        Pass_6->setGeometry(QRect(70, 210, 311, 41));
        Pass_6->setEchoMode(QLineEdit::Password);
        back_21 = new QPushButton(signin);
        back_21->setObjectName("back_21");
        back_21->setGeometry(QRect(190, 340, 80, 24));
        stackedWidget->addWidget(signin);
        menu = new QWidget();
        menu->setObjectName("menu");
        img_3 = new QLabel(menu);
        img_3->setObjectName("img_3");
        img_3->setGeometry(QRect(0, 0, 700, 400));
        img_3->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_3->setScaledContents(true);
        text_10 = new QLabel(menu);
        text_10->setObjectName("text_10");
        text_10->setGeometry(QRect(290, 60, 191, 81));
        text_10->setFont(font2);
        text_10->setFocusPolicy(Qt::NoFocus);
        text_10->setAcceptDrops(false);
        text_10->setAutoFillBackground(false);
        text_10->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_10->setTextFormat(Qt::AutoText);
        text_10->setScaledContents(false);
        Logout_2 = new QPushButton(menu);
        Logout_2->setObjectName("Logout_2");
        Logout_2->setGeometry(QRect(580, 30, 80, 24));
        Cancel_2 = new QPushButton(menu);
        Cancel_2->setObjectName("Cancel_2");
        Cancel_2->setGeometry(QRect(170, 280, 381, 41));
        Book_2 = new QPushButton(menu);
        Book_2->setObjectName("Book_2");
        Book_2->setGeometry(QRect(170, 140, 381, 41));
        History_2 = new QPushButton(menu);
        History_2->setObjectName("History_2");
        History_2->setGeometry(QRect(170, 210, 381, 41));
        stackedWidget->addWidget(menu);
        spc = new QWidget();
        spc->setObjectName("spc");
        img_4 = new QLabel(spc);
        img_4->setObjectName("img_4");
        img_4->setGeometry(QRect(0, 0, 700, 400));
        img_4->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_4->setScaledContents(true);
        sp_9 = new QCommandLinkButton(spc);
        sp_9->setObjectName("sp_9");
        sp_9->setGeometry(QRect(460, 250, 168, 41));
        sp_10 = new QCommandLinkButton(spc);
        sp_10->setObjectName("sp_10");
        sp_10->setGeometry(QRect(460, 150, 168, 41));
        text_11 = new QLabel(spc);
        text_11->setObjectName("text_11");
        text_11->setGeometry(QRect(250, 60, 301, 71));
        text_11->setFont(font2);
        text_11->setFocusPolicy(Qt::NoFocus);
        text_11->setAcceptDrops(false);
        text_11->setAutoFillBackground(false);
        text_11->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_11->setTextFormat(Qt::AutoText);
        text_11->setScaledContents(false);
        sp_4 = new QCommandLinkButton(spc);
        sp_4->setObjectName("sp_4");
        sp_4->setGeometry(QRect(200, 200, 168, 41));
        sp_5 = new QCommandLinkButton(spc);
        sp_5->setObjectName("sp_5");
        sp_5->setGeometry(QRect(200, 150, 168, 41));
        sp_11 = new QCommandLinkButton(spc);
        sp_11->setObjectName("sp_11");
        sp_11->setGeometry(QRect(200, 250, 168, 41));
        sp_12 = new QCommandLinkButton(spc);
        sp_12->setObjectName("sp_12");
        sp_12->setGeometry(QRect(460, 200, 168, 41));
        back = new QPushButton(spc);
        back->setObjectName("back");
        back->setGeometry(QRect(340, 330, 80, 24));
        back->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(spc);
        slot = new QWidget();
        slot->setObjectName("slot");
        img_5 = new QLabel(slot);
        img_5->setObjectName("img_5");
        img_5->setGeometry(QRect(0, 0, 700, 400));
        img_5->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img3.jpg")));
        img_5->setScaledContents(true);
        book_2 = new QPushButton(slot);
        book_2->setObjectName("book_2");
        book_2->setGeometry(QRect(360, 340, 80, 24));
        book_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        text_12 = new QLabel(slot);
        text_12->setObjectName("text_12");
        text_12->setGeometry(QRect(290, 20, 301, 71));
        text_12->setFont(font2);
        text_12->setFocusPolicy(Qt::NoFocus);
        text_12->setAcceptDrops(false);
        text_12->setAutoFillBackground(false);
        text_12->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_12->setTextFormat(Qt::AutoText);
        text_12->setScaledContents(false);
        back_2 = new QPushButton(slot);
        back_2->setObjectName("back_2");
        back_2->setGeometry(QRect(270, 340, 80, 24));
        back_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        pat_name = new QLineEdit(slot);
        pat_name->setObjectName("pat_name");
        pat_name->setGeometry(QRect(220, 90, 311, 21));
        text_2 = new QLabel(slot);
        text_2->setObjectName("text_2");
        text_2->setGeometry(QRect(110, 90, 101, 16));
        text_2->setMaximumSize(QSize(16777215, 16777215));
        QFont font3;
        font3.setPointSize(10);
        text_2->setFont(font3);
        doc_name = new QLineEdit(slot);
        doc_name->setObjectName("doc_name");
        doc_name->setGeometry(QRect(220, 170, 311, 21));
        selected_slot = new QLineEdit(slot);
        selected_slot->setObjectName("selected_slot");
        selected_slot->setGeometry(QRect(220, 210, 311, 21));
        text_3 = new QLabel(slot);
        text_3->setObjectName("text_3");
        text_3->setGeometry(QRect(110, 170, 91, 16));
        text_3->setMaximumSize(QSize(16777215, 16777215));
        text_3->setFont(font3);
        text_4 = new QLabel(slot);
        text_4->setObjectName("text_4");
        text_4->setGeometry(QRect(110, 210, 91, 16));
        text_4->setMaximumSize(QSize(16777215, 16777215));
        text_4->setFont(font3);
        text_5 = new QLabel(slot);
        text_5->setObjectName("text_5");
        text_5->setGeometry(QRect(110, 130, 91, 21));
        text_5->setMaximumSize(QSize(16777215, 16777215));
        text_5->setFont(font3);
        patient_age = new QLineEdit(slot);
        patient_age->setObjectName("patient_age");
        patient_age->setGeometry(QRect(220, 130, 311, 21));
        contact_no = new QLineEdit(slot);
        contact_no->setObjectName("contact_no");
        contact_no->setGeometry(QRect(220, 250, 311, 21));
        text_59 = new QLabel(slot);
        text_59->setObjectName("text_59");
        text_59->setGeometry(QRect(110, 250, 91, 16));
        text_59->setMaximumSize(QSize(16777215, 16777215));
        text_59->setFont(font3);
        a_pass = new QLineEdit(slot);
        a_pass->setObjectName("a_pass");
        a_pass->setGeometry(QRect(220, 290, 311, 21));
        a_pass->setEchoMode(QLineEdit::Password);
        text_64 = new QLabel(slot);
        text_64->setObjectName("text_64");
        text_64->setGeometry(QRect(110, 290, 91, 16));
        text_64->setMaximumSize(QSize(16777215, 16777215));
        text_64->setFont(font3);
        stackedWidget->addWidget(slot);
        doctor = new QWidget();
        doctor->setObjectName("doctor");
        img_6 = new QLabel(doctor);
        img_6->setObjectName("img_6");
        img_6->setGeometry(QRect(0, 0, 700, 400));
        img_6->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_6->setScaledContents(true);
        text_13 = new QLabel(doctor);
        text_13->setObjectName("text_13");
        text_13->setGeometry(QRect(270, 60, 191, 81));
        text_13->setFont(font2);
        text_13->setFocusPolicy(Qt::NoFocus);
        text_13->setAcceptDrops(false);
        text_13->setAutoFillBackground(false);
        text_13->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_13->setTextFormat(Qt::AutoText);
        text_13->setScaledContents(false);
        doc_5 = new QRadioButton(doctor);
        doc_5->setObjectName("doc_5");
        doc_5->setGeometry(QRect(270, 180, 201, 21));
        next_2 = new QPushButton(doctor);
        next_2->setObjectName("next_2");
        next_2->setGeometry(QRect(370, 330, 80, 24));
        next_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        doc_6 = new QRadioButton(doctor);
        doc_6->setObjectName("doc_6");
        doc_6->setGeometry(QRect(270, 150, 201, 21));
        back_3 = new QPushButton(doctor);
        back_3->setObjectName("back_3");
        back_3->setGeometry(QRect(280, 330, 80, 24));
        back_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor);
        det = new QWidget();
        det->setObjectName("det");
        img_7 = new QLabel(det);
        img_7->setObjectName("img_7");
        img_7->setGeometry(QRect(-30, 30, 490, 320));
        img_7->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img4.jpg")));
        img_7->setScaledContents(true);
        push_3 = new QCommandLinkButton(det);
        push_3->setObjectName("push_3");
        push_3->setGeometry(QRect(660, 180, 31, 41));
        QIcon icon;
        icon.addFile(QString::fromUtf8("../Resourses/next_icon.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        push_3->setIcon(icon);
        push_16 = new QCommandLinkButton(det);
        push_16->setObjectName("push_16");
        push_16->setGeometry(QRect(10, 180, 31, 41));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../Resourses/back_icon.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        push_16->setIcon(icon1);
        img_16 = new QLabel(det);
        img_16->setObjectName("img_16");
        img_16->setGeometry(QRect(0, 0, 700, 410));
        img_16->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        text_21 = new QLabel(det);
        text_21->setObjectName("text_21");
        text_21->setGeometry(QRect(460, 30, 141, 71));
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Arial Rounded MT Bold")});
        font4.setPointSize(16);
        font4.setBold(false);
        text_21->setFont(font4);
        text_21->setFocusPolicy(Qt::NoFocus);
        text_21->setAcceptDrops(false);
        text_21->setAutoFillBackground(false);
        text_21->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_21->setTextFormat(Qt::AutoText);
        text_21->setScaledContents(false);
        sl_2 = new QCommandLinkButton(det);
        sl_2->setObjectName("sl_2");
        sl_2->setGeometry(QRect(450, 120, 168, 41));
        sl_3 = new QCommandLinkButton(det);
        sl_3->setObjectName("sl_3");
        sl_3->setGeometry(QRect(450, 150, 168, 41));
        sl_5 = new QCommandLinkButton(det);
        sl_5->setObjectName("sl_5");
        sl_5->setGeometry(QRect(450, 210, 168, 41));
        sl_6 = new QCommandLinkButton(det);
        sl_6->setObjectName("sl_6");
        sl_6->setGeometry(QRect(450, 240, 168, 41));
        sl_7 = new QCommandLinkButton(det);
        sl_7->setObjectName("sl_7");
        sl_7->setGeometry(QRect(450, 270, 168, 41));
        sl = new QCommandLinkButton(det);
        sl->setObjectName("sl");
        sl->setGeometry(QRect(450, 90, 168, 41));
        sl_4 = new QCommandLinkButton(det);
        sl_4->setObjectName("sl_4");
        sl_4->setGeometry(QRect(450, 180, 168, 41));
        sl_8 = new QCommandLinkButton(det);
        sl_8->setObjectName("sl_8");
        sl_8->setGeometry(QRect(450, 300, 168, 41));
        stackedWidget->addWidget(det);
        img_16->raise();
        img_7->raise();
        push_16->raise();
        sl_6->raise();
        sl_5->raise();
        sl_3->raise();
        sl_2->raise();
        push_3->raise();
        text_21->raise();
        sl_7->raise();
        sl->raise();
        sl_4->raise();
        sl_8->raise();
        det_2 = new QWidget();
        det_2->setObjectName("det_2");
        img_8 = new QLabel(det_2);
        img_8->setObjectName("img_8");
        img_8->setGeometry(QRect(-30, 30, 490, 320));
        img_8->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img5.jpg")));
        img_8->setScaledContents(true);
        push_4 = new QCommandLinkButton(det_2);
        push_4->setObjectName("push_4");
        push_4->setGeometry(QRect(660, 180, 31, 41));
        push_4->setIcon(icon);
        push_17 = new QCommandLinkButton(det_2);
        push_17->setObjectName("push_17");
        push_17->setGeometry(QRect(10, 180, 31, 41));
        push_17->setIcon(icon1);
        img_17 = new QLabel(det_2);
        img_17->setObjectName("img_17");
        img_17->setGeometry(QRect(0, 0, 700, 410));
        img_17->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        sl_9 = new QCommandLinkButton(det_2);
        sl_9->setObjectName("sl_9");
        sl_9->setGeometry(QRect(410, 90, 168, 41));
        text_22 = new QLabel(det_2);
        text_22->setObjectName("text_22");
        text_22->setGeometry(QRect(420, 30, 141, 71));
        text_22->setFont(font4);
        text_22->setFocusPolicy(Qt::NoFocus);
        text_22->setAcceptDrops(false);
        text_22->setAutoFillBackground(false);
        text_22->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_22->setTextFormat(Qt::AutoText);
        text_22->setScaledContents(false);
        sl_10 = new QCommandLinkButton(det_2);
        sl_10->setObjectName("sl_10");
        sl_10->setGeometry(QRect(410, 180, 168, 41));
        sl_11 = new QCommandLinkButton(det_2);
        sl_11->setObjectName("sl_11");
        sl_11->setGeometry(QRect(410, 300, 168, 41));
        sl_12 = new QCommandLinkButton(det_2);
        sl_12->setObjectName("sl_12");
        sl_12->setGeometry(QRect(410, 150, 168, 41));
        sl_13 = new QCommandLinkButton(det_2);
        sl_13->setObjectName("sl_13");
        sl_13->setGeometry(QRect(410, 210, 168, 41));
        sl_14 = new QCommandLinkButton(det_2);
        sl_14->setObjectName("sl_14");
        sl_14->setGeometry(QRect(410, 120, 168, 41));
        sl_15 = new QCommandLinkButton(det_2);
        sl_15->setObjectName("sl_15");
        sl_15->setGeometry(QRect(410, 240, 168, 41));
        sl_16 = new QCommandLinkButton(det_2);
        sl_16->setObjectName("sl_16");
        sl_16->setGeometry(QRect(410, 270, 168, 41));
        stackedWidget->addWidget(det_2);
        img_17->raise();
        img_8->raise();
        push_4->raise();
        push_17->raise();
        sl_9->raise();
        text_22->raise();
        sl_10->raise();
        sl_11->raise();
        sl_12->raise();
        sl_13->raise();
        sl_14->raise();
        sl_15->raise();
        sl_16->raise();
        doctor_7 = new QWidget();
        doctor_7->setObjectName("doctor_7");
        doctor_7->setMinimumSize(QSize(700, 0));
        img_9 = new QLabel(doctor_7);
        img_9->setObjectName("img_9");
        img_9->setGeometry(QRect(0, 0, 700, 400));
        img_9->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_9->setScaledContents(true);
        doc_9 = new QRadioButton(doctor_7);
        doc_9->setObjectName("doc_9");
        doc_9->setGeometry(QRect(260, 160, 211, 21));
        doc_10 = new QRadioButton(doctor_7);
        doc_10->setObjectName("doc_10");
        doc_10->setGeometry(QRect(260, 200, 211, 22));
        text_15 = new QLabel(doctor_7);
        text_15->setObjectName("text_15");
        text_15->setGeometry(QRect(260, 70, 191, 81));
        text_15->setFont(font2);
        text_15->setFocusPolicy(Qt::NoFocus);
        text_15->setAcceptDrops(false);
        text_15->setAutoFillBackground(false);
        text_15->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_15->setTextFormat(Qt::AutoText);
        text_15->setScaledContents(false);
        next_4 = new QPushButton(doctor_7);
        next_4->setObjectName("next_4");
        next_4->setGeometry(QRect(360, 330, 80, 24));
        next_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        back_4 = new QPushButton(doctor_7);
        back_4->setObjectName("back_4");
        back_4->setGeometry(QRect(270, 330, 80, 24));
        back_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor_7);
        det_3 = new QWidget();
        det_3->setObjectName("det_3");
        img_23 = new QLabel(det_3);
        img_23->setObjectName("img_23");
        img_23->setGeometry(QRect(10, 30, 451, 320));
        img_23->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img8.png")));
        img_23->setScaledContents(true);
        push_7 = new QCommandLinkButton(det_3);
        push_7->setObjectName("push_7");
        push_7->setGeometry(QRect(660, 180, 31, 41));
        push_7->setIcon(icon);
        push_18 = new QCommandLinkButton(det_3);
        push_18->setObjectName("push_18");
        push_18->setGeometry(QRect(10, 180, 31, 41));
        push_18->setIcon(icon1);
        sl_17 = new QCommandLinkButton(det_3);
        sl_17->setObjectName("sl_17");
        sl_17->setGeometry(QRect(460, 270, 168, 41));
        sl_18 = new QCommandLinkButton(det_3);
        sl_18->setObjectName("sl_18");
        sl_18->setGeometry(QRect(460, 300, 168, 41));
        sl_19 = new QCommandLinkButton(det_3);
        sl_19->setObjectName("sl_19");
        sl_19->setGeometry(QRect(460, 240, 168, 41));
        sl_20 = new QCommandLinkButton(det_3);
        sl_20->setObjectName("sl_20");
        sl_20->setGeometry(QRect(460, 150, 168, 41));
        sl_21 = new QCommandLinkButton(det_3);
        sl_21->setObjectName("sl_21");
        sl_21->setGeometry(QRect(460, 120, 168, 41));
        sl_22 = new QCommandLinkButton(det_3);
        sl_22->setObjectName("sl_22");
        sl_22->setGeometry(QRect(460, 210, 168, 41));
        sl_23 = new QCommandLinkButton(det_3);
        sl_23->setObjectName("sl_23");
        sl_23->setGeometry(QRect(460, 90, 168, 41));
        text_23 = new QLabel(det_3);
        text_23->setObjectName("text_23");
        text_23->setGeometry(QRect(470, 30, 141, 71));
        text_23->setFont(font4);
        text_23->setFocusPolicy(Qt::NoFocus);
        text_23->setAcceptDrops(false);
        text_23->setAutoFillBackground(false);
        text_23->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_23->setTextFormat(Qt::AutoText);
        text_23->setScaledContents(false);
        sl_24 = new QCommandLinkButton(det_3);
        sl_24->setObjectName("sl_24");
        sl_24->setGeometry(QRect(460, 180, 168, 41));
        img_18 = new QLabel(det_3);
        img_18->setObjectName("img_18");
        img_18->setGeometry(QRect(0, 0, 700, 410));
        img_18->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_3);
        img_18->raise();
        img_23->raise();
        push_7->raise();
        push_18->raise();
        sl_17->raise();
        sl_18->raise();
        sl_19->raise();
        sl_20->raise();
        sl_21->raise();
        sl_22->raise();
        sl_23->raise();
        text_23->raise();
        sl_24->raise();
        det_4 = new QWidget();
        det_4->setObjectName("det_4");
        img_24 = new QLabel(det_4);
        img_24->setObjectName("img_24");
        img_24->setGeometry(QRect(-30, 30, 490, 320));
        img_24->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img9.png")));
        img_24->setScaledContents(true);
        push_8 = new QCommandLinkButton(det_4);
        push_8->setObjectName("push_8");
        push_8->setGeometry(QRect(660, 180, 168, 41));
        push_8->setIcon(icon);
        push_19 = new QCommandLinkButton(det_4);
        push_19->setObjectName("push_19");
        push_19->setGeometry(QRect(10, 180, 31, 41));
        push_19->setIcon(icon1);
        sl_25 = new QCommandLinkButton(det_4);
        sl_25->setObjectName("sl_25");
        sl_25->setGeometry(QRect(430, 270, 168, 41));
        sl_26 = new QCommandLinkButton(det_4);
        sl_26->setObjectName("sl_26");
        sl_26->setGeometry(QRect(430, 300, 168, 41));
        sl_27 = new QCommandLinkButton(det_4);
        sl_27->setObjectName("sl_27");
        sl_27->setGeometry(QRect(430, 240, 168, 41));
        sl_28 = new QCommandLinkButton(det_4);
        sl_28->setObjectName("sl_28");
        sl_28->setGeometry(QRect(430, 150, 168, 41));
        sl_29 = new QCommandLinkButton(det_4);
        sl_29->setObjectName("sl_29");
        sl_29->setGeometry(QRect(430, 120, 168, 41));
        sl_30 = new QCommandLinkButton(det_4);
        sl_30->setObjectName("sl_30");
        sl_30->setGeometry(QRect(430, 210, 168, 41));
        sl_31 = new QCommandLinkButton(det_4);
        sl_31->setObjectName("sl_31");
        sl_31->setGeometry(QRect(430, 90, 168, 41));
        text_24 = new QLabel(det_4);
        text_24->setObjectName("text_24");
        text_24->setGeometry(QRect(440, 30, 141, 71));
        text_24->setFont(font4);
        text_24->setFocusPolicy(Qt::NoFocus);
        text_24->setAcceptDrops(false);
        text_24->setAutoFillBackground(false);
        text_24->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_24->setTextFormat(Qt::AutoText);
        text_24->setScaledContents(false);
        sl_32 = new QCommandLinkButton(det_4);
        sl_32->setObjectName("sl_32");
        sl_32->setGeometry(QRect(430, 180, 168, 41));
        img_19 = new QLabel(det_4);
        img_19->setObjectName("img_19");
        img_19->setGeometry(QRect(0, 0, 700, 410));
        img_19->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_4);
        img_19->raise();
        img_24->raise();
        push_8->raise();
        push_19->raise();
        sl_25->raise();
        sl_26->raise();
        sl_27->raise();
        sl_28->raise();
        sl_29->raise();
        sl_30->raise();
        sl_31->raise();
        text_24->raise();
        sl_32->raise();
        doctor_3 = new QWidget();
        doctor_3->setObjectName("doctor_3");
        img_10 = new QLabel(doctor_3);
        img_10->setObjectName("img_10");
        img_10->setGeometry(QRect(0, 0, 700, 400));
        img_10->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_10->setScaledContents(true);
        text_16 = new QLabel(doctor_3);
        text_16->setObjectName("text_16");
        text_16->setGeometry(QRect(260, 60, 191, 81));
        text_16->setFont(font2);
        text_16->setFocusPolicy(Qt::NoFocus);
        text_16->setAcceptDrops(false);
        text_16->setAutoFillBackground(false);
        text_16->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_16->setTextFormat(Qt::AutoText);
        text_16->setScaledContents(false);
        doc_11 = new QRadioButton(doctor_3);
        doc_11->setObjectName("doc_11");
        doc_11->setGeometry(QRect(260, 160, 161, 22));
        doc_12 = new QRadioButton(doctor_3);
        doc_12->setObjectName("doc_12");
        doc_12->setGeometry(QRect(260, 200, 221, 22));
        next_5 = new QPushButton(doctor_3);
        next_5->setObjectName("next_5");
        next_5->setGeometry(QRect(360, 320, 80, 24));
        next_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        back_5 = new QPushButton(doctor_3);
        back_5->setObjectName("back_5");
        back_5->setGeometry(QRect(270, 320, 80, 24));
        back_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor_3);
        det_5 = new QWidget();
        det_5->setObjectName("det_5");
        img_25 = new QLabel(det_5);
        img_25->setObjectName("img_25");
        img_25->setGeometry(QRect(-30, 30, 490, 320));
        img_25->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img_10.png")));
        img_25->setScaledContents(true);
        push_9 = new QCommandLinkButton(det_5);
        push_9->setObjectName("push_9");
        push_9->setGeometry(QRect(650, 180, 168, 41));
        push_9->setIcon(icon);
        push_20 = new QCommandLinkButton(det_5);
        push_20->setObjectName("push_20");
        push_20->setGeometry(QRect(10, 180, 31, 41));
        push_20->setIcon(icon1);
        sl_33 = new QCommandLinkButton(det_5);
        sl_33->setObjectName("sl_33");
        sl_33->setGeometry(QRect(460, 270, 168, 41));
        sl_34 = new QCommandLinkButton(det_5);
        sl_34->setObjectName("sl_34");
        sl_34->setGeometry(QRect(460, 300, 168, 41));
        sl_35 = new QCommandLinkButton(det_5);
        sl_35->setObjectName("sl_35");
        sl_35->setGeometry(QRect(460, 240, 168, 41));
        sl_36 = new QCommandLinkButton(det_5);
        sl_36->setObjectName("sl_36");
        sl_36->setGeometry(QRect(460, 150, 168, 41));
        sl_37 = new QCommandLinkButton(det_5);
        sl_37->setObjectName("sl_37");
        sl_37->setGeometry(QRect(460, 120, 168, 41));
        sl_38 = new QCommandLinkButton(det_5);
        sl_38->setObjectName("sl_38");
        sl_38->setGeometry(QRect(460, 210, 168, 41));
        sl_39 = new QCommandLinkButton(det_5);
        sl_39->setObjectName("sl_39");
        sl_39->setGeometry(QRect(460, 90, 168, 41));
        text_25 = new QLabel(det_5);
        text_25->setObjectName("text_25");
        text_25->setGeometry(QRect(470, 30, 141, 71));
        text_25->setFont(font4);
        text_25->setFocusPolicy(Qt::NoFocus);
        text_25->setAcceptDrops(false);
        text_25->setAutoFillBackground(false);
        text_25->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_25->setTextFormat(Qt::AutoText);
        text_25->setScaledContents(false);
        sl_40 = new QCommandLinkButton(det_5);
        sl_40->setObjectName("sl_40");
        sl_40->setGeometry(QRect(460, 180, 168, 41));
        img_29 = new QLabel(det_5);
        img_29->setObjectName("img_29");
        img_29->setGeometry(QRect(0, 0, 700, 410));
        img_29->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_5);
        img_29->raise();
        img_25->raise();
        push_9->raise();
        push_20->raise();
        sl_33->raise();
        sl_34->raise();
        sl_35->raise();
        sl_36->raise();
        sl_37->raise();
        sl_38->raise();
        sl_39->raise();
        text_25->raise();
        sl_40->raise();
        det_6 = new QWidget();
        det_6->setObjectName("det_6");
        img_26 = new QLabel(det_6);
        img_26->setObjectName("img_26");
        img_26->setGeometry(QRect(-30, 30, 490, 320));
        img_26->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img_11.png")));
        img_26->setScaledContents(true);
        push_10 = new QCommandLinkButton(det_6);
        push_10->setObjectName("push_10");
        push_10->setGeometry(QRect(650, 190, 168, 41));
        push_10->setIcon(icon);
        push_21 = new QCommandLinkButton(det_6);
        push_21->setObjectName("push_21");
        push_21->setGeometry(QRect(10, 190, 31, 41));
        push_21->setIcon(icon1);
        sl_41 = new QCommandLinkButton(det_6);
        sl_41->setObjectName("sl_41");
        sl_41->setGeometry(QRect(470, 270, 168, 41));
        sl_42 = new QCommandLinkButton(det_6);
        sl_42->setObjectName("sl_42");
        sl_42->setGeometry(QRect(470, 300, 168, 41));
        sl_43 = new QCommandLinkButton(det_6);
        sl_43->setObjectName("sl_43");
        sl_43->setGeometry(QRect(470, 240, 168, 41));
        sl_44 = new QCommandLinkButton(det_6);
        sl_44->setObjectName("sl_44");
        sl_44->setGeometry(QRect(470, 150, 168, 41));
        sl_45 = new QCommandLinkButton(det_6);
        sl_45->setObjectName("sl_45");
        sl_45->setGeometry(QRect(470, 120, 168, 41));
        sl_46 = new QCommandLinkButton(det_6);
        sl_46->setObjectName("sl_46");
        sl_46->setGeometry(QRect(470, 210, 168, 41));
        sl_47 = new QCommandLinkButton(det_6);
        sl_47->setObjectName("sl_47");
        sl_47->setGeometry(QRect(470, 90, 168, 41));
        text_26 = new QLabel(det_6);
        text_26->setObjectName("text_26");
        text_26->setGeometry(QRect(480, 30, 141, 71));
        text_26->setFont(font4);
        text_26->setFocusPolicy(Qt::NoFocus);
        text_26->setAcceptDrops(false);
        text_26->setAutoFillBackground(false);
        text_26->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_26->setTextFormat(Qt::AutoText);
        text_26->setScaledContents(false);
        sl_48 = new QCommandLinkButton(det_6);
        sl_48->setObjectName("sl_48");
        sl_48->setGeometry(QRect(470, 180, 168, 41));
        img_31 = new QLabel(det_6);
        img_31->setObjectName("img_31");
        img_31->setGeometry(QRect(0, 0, 700, 410));
        img_31->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_6);
        img_31->raise();
        img_26->raise();
        push_10->raise();
        push_21->raise();
        sl_41->raise();
        sl_42->raise();
        sl_43->raise();
        sl_44->raise();
        sl_45->raise();
        sl_46->raise();
        sl_47->raise();
        text_26->raise();
        sl_48->raise();
        doctor_4 = new QWidget();
        doctor_4->setObjectName("doctor_4");
        img_11 = new QLabel(doctor_4);
        img_11->setObjectName("img_11");
        img_11->setGeometry(QRect(0, 0, 700, 400));
        img_11->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_11->setScaledContents(true);
        text_17 = new QLabel(doctor_4);
        text_17->setObjectName("text_17");
        text_17->setGeometry(QRect(260, 70, 191, 81));
        text_17->setFont(font2);
        text_17->setFocusPolicy(Qt::NoFocus);
        text_17->setAcceptDrops(false);
        text_17->setAutoFillBackground(false);
        text_17->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_17->setTextFormat(Qt::AutoText);
        text_17->setScaledContents(false);
        doc_13 = new QRadioButton(doctor_4);
        doc_13->setObjectName("doc_13");
        doc_13->setGeometry(QRect(260, 160, 241, 22));
        doc_14 = new QRadioButton(doctor_4);
        doc_14->setObjectName("doc_14");
        doc_14->setGeometry(QRect(260, 200, 221, 22));
        next_6 = new QPushButton(doctor_4);
        next_6->setObjectName("next_6");
        next_6->setGeometry(QRect(350, 320, 80, 24));
        next_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        back_6 = new QPushButton(doctor_4);
        back_6->setObjectName("back_6");
        back_6->setGeometry(QRect(260, 320, 80, 24));
        back_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor_4);
        det_7 = new QWidget();
        det_7->setObjectName("det_7");
        img_27 = new QLabel(det_7);
        img_27->setObjectName("img_27");
        img_27->setGeometry(QRect(20, 40, 431, 320));
        img_27->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img13.png")));
        img_27->setScaledContents(true);
        push_11 = new QCommandLinkButton(det_7);
        push_11->setObjectName("push_11");
        push_11->setGeometry(QRect(650, 180, 168, 41));
        push_11->setIcon(icon);
        push_22 = new QCommandLinkButton(det_7);
        push_22->setObjectName("push_22");
        push_22->setGeometry(QRect(10, 180, 31, 41));
        push_22->setIcon(icon1);
        sl_49 = new QCommandLinkButton(det_7);
        sl_49->setObjectName("sl_49");
        sl_49->setGeometry(QRect(450, 270, 168, 41));
        sl_50 = new QCommandLinkButton(det_7);
        sl_50->setObjectName("sl_50");
        sl_50->setGeometry(QRect(450, 300, 168, 41));
        sl_51 = new QCommandLinkButton(det_7);
        sl_51->setObjectName("sl_51");
        sl_51->setGeometry(QRect(450, 240, 168, 41));
        sl_52 = new QCommandLinkButton(det_7);
        sl_52->setObjectName("sl_52");
        sl_52->setGeometry(QRect(450, 150, 168, 41));
        sl_53 = new QCommandLinkButton(det_7);
        sl_53->setObjectName("sl_53");
        sl_53->setGeometry(QRect(450, 120, 168, 41));
        sl_54 = new QCommandLinkButton(det_7);
        sl_54->setObjectName("sl_54");
        sl_54->setGeometry(QRect(450, 210, 168, 41));
        sl_55 = new QCommandLinkButton(det_7);
        sl_55->setObjectName("sl_55");
        sl_55->setGeometry(QRect(450, 90, 168, 41));
        text_27 = new QLabel(det_7);
        text_27->setObjectName("text_27");
        text_27->setGeometry(QRect(460, 30, 141, 71));
        text_27->setFont(font4);
        text_27->setFocusPolicy(Qt::NoFocus);
        text_27->setAcceptDrops(false);
        text_27->setAutoFillBackground(false);
        text_27->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_27->setTextFormat(Qt::AutoText);
        text_27->setScaledContents(false);
        sl_56 = new QCommandLinkButton(det_7);
        sl_56->setObjectName("sl_56");
        sl_56->setGeometry(QRect(450, 180, 168, 41));
        img_32 = new QLabel(det_7);
        img_32->setObjectName("img_32");
        img_32->setGeometry(QRect(0, 0, 700, 410));
        img_32->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_7);
        img_32->raise();
        img_27->raise();
        push_11->raise();
        push_22->raise();
        sl_49->raise();
        sl_50->raise();
        sl_51->raise();
        sl_52->raise();
        sl_53->raise();
        sl_54->raise();
        sl_55->raise();
        text_27->raise();
        sl_56->raise();
        det_8 = new QWidget();
        det_8->setObjectName("det_8");
        img_28 = new QLabel(det_8);
        img_28->setObjectName("img_28");
        img_28->setGeometry(QRect(-30, 30, 490, 320));
        img_28->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img12.png")));
        img_28->setScaledContents(true);
        push_12 = new QCommandLinkButton(det_8);
        push_12->setObjectName("push_12");
        push_12->setGeometry(QRect(660, 180, 168, 41));
        push_12->setIcon(icon);
        push_23 = new QCommandLinkButton(det_8);
        push_23->setObjectName("push_23");
        push_23->setGeometry(QRect(10, 190, 31, 41));
        push_23->setIcon(icon1);
        sl_57 = new QCommandLinkButton(det_8);
        sl_57->setObjectName("sl_57");
        sl_57->setGeometry(QRect(480, 260, 168, 41));
        sl_58 = new QCommandLinkButton(det_8);
        sl_58->setObjectName("sl_58");
        sl_58->setGeometry(QRect(480, 290, 168, 41));
        sl_59 = new QCommandLinkButton(det_8);
        sl_59->setObjectName("sl_59");
        sl_59->setGeometry(QRect(480, 230, 168, 41));
        sl_60 = new QCommandLinkButton(det_8);
        sl_60->setObjectName("sl_60");
        sl_60->setGeometry(QRect(480, 140, 168, 41));
        sl_61 = new QCommandLinkButton(det_8);
        sl_61->setObjectName("sl_61");
        sl_61->setGeometry(QRect(480, 110, 168, 41));
        sl_62 = new QCommandLinkButton(det_8);
        sl_62->setObjectName("sl_62");
        sl_62->setGeometry(QRect(480, 200, 168, 41));
        sl_63 = new QCommandLinkButton(det_8);
        sl_63->setObjectName("sl_63");
        sl_63->setGeometry(QRect(480, 80, 168, 41));
        text_28 = new QLabel(det_8);
        text_28->setObjectName("text_28");
        text_28->setGeometry(QRect(490, 20, 141, 71));
        text_28->setFont(font4);
        text_28->setFocusPolicy(Qt::NoFocus);
        text_28->setAcceptDrops(false);
        text_28->setAutoFillBackground(false);
        text_28->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_28->setTextFormat(Qt::AutoText);
        text_28->setScaledContents(false);
        sl_64 = new QCommandLinkButton(det_8);
        sl_64->setObjectName("sl_64");
        sl_64->setGeometry(QRect(480, 170, 168, 41));
        img_33 = new QLabel(det_8);
        img_33->setObjectName("img_33");
        img_33->setGeometry(QRect(0, 0, 700, 410));
        img_33->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_8);
        img_33->raise();
        img_28->raise();
        push_12->raise();
        push_23->raise();
        sl_57->raise();
        sl_58->raise();
        sl_59->raise();
        sl_60->raise();
        sl_61->raise();
        sl_62->raise();
        sl_63->raise();
        text_28->raise();
        sl_64->raise();
        doctor_5 = new QWidget();
        doctor_5->setObjectName("doctor_5");
        img_12 = new QLabel(doctor_5);
        img_12->setObjectName("img_12");
        img_12->setGeometry(QRect(0, 0, 700, 400));
        img_12->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_12->setScaledContents(true);
        text_18 = new QLabel(doctor_5);
        text_18->setObjectName("text_18");
        text_18->setGeometry(QRect(260, 80, 191, 81));
        text_18->setFont(font2);
        text_18->setFocusPolicy(Qt::NoFocus);
        text_18->setAcceptDrops(false);
        text_18->setAutoFillBackground(false);
        text_18->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_18->setTextFormat(Qt::AutoText);
        text_18->setScaledContents(false);
        doc_15 = new QRadioButton(doctor_5);
        doc_15->setObjectName("doc_15");
        doc_15->setGeometry(QRect(260, 170, 241, 22));
        doc_16 = new QRadioButton(doctor_5);
        doc_16->setObjectName("doc_16");
        doc_16->setGeometry(QRect(260, 210, 221, 22));
        next_7 = new QPushButton(doctor_5);
        next_7->setObjectName("next_7");
        next_7->setGeometry(QRect(360, 320, 80, 24));
        next_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        back_7 = new QPushButton(doctor_5);
        back_7->setObjectName("back_7");
        back_7->setGeometry(QRect(270, 320, 80, 24));
        back_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor_5);
        det_9 = new QWidget();
        det_9->setObjectName("det_9");
        img_13 = new QLabel(det_9);
        img_13->setObjectName("img_13");
        img_13->setGeometry(QRect(-30, 30, 490, 320));
        img_13->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img14.png")));
        img_13->setScaledContents(true);
        push_13 = new QCommandLinkButton(det_9);
        push_13->setObjectName("push_13");
        push_13->setGeometry(QRect(660, 180, 168, 41));
        push_13->setIcon(icon);
        push_24 = new QCommandLinkButton(det_9);
        push_24->setObjectName("push_24");
        push_24->setGeometry(QRect(10, 180, 31, 41));
        push_24->setIcon(icon1);
        sl_65 = new QCommandLinkButton(det_9);
        sl_65->setObjectName("sl_65");
        sl_65->setGeometry(QRect(440, 280, 168, 41));
        sl_66 = new QCommandLinkButton(det_9);
        sl_66->setObjectName("sl_66");
        sl_66->setGeometry(QRect(440, 310, 168, 41));
        sl_67 = new QCommandLinkButton(det_9);
        sl_67->setObjectName("sl_67");
        sl_67->setGeometry(QRect(440, 250, 168, 41));
        sl_68 = new QCommandLinkButton(det_9);
        sl_68->setObjectName("sl_68");
        sl_68->setGeometry(QRect(440, 160, 168, 41));
        sl_69 = new QCommandLinkButton(det_9);
        sl_69->setObjectName("sl_69");
        sl_69->setGeometry(QRect(440, 130, 168, 41));
        sl_70 = new QCommandLinkButton(det_9);
        sl_70->setObjectName("sl_70");
        sl_70->setGeometry(QRect(440, 220, 168, 41));
        sl_71 = new QCommandLinkButton(det_9);
        sl_71->setObjectName("sl_71");
        sl_71->setGeometry(QRect(440, 100, 168, 41));
        text_29 = new QLabel(det_9);
        text_29->setObjectName("text_29");
        text_29->setGeometry(QRect(450, 40, 141, 71));
        text_29->setFont(font4);
        text_29->setFocusPolicy(Qt::NoFocus);
        text_29->setAcceptDrops(false);
        text_29->setAutoFillBackground(false);
        text_29->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_29->setTextFormat(Qt::AutoText);
        text_29->setScaledContents(false);
        sl_72 = new QCommandLinkButton(det_9);
        sl_72->setObjectName("sl_72");
        sl_72->setGeometry(QRect(440, 190, 168, 41));
        img_34 = new QLabel(det_9);
        img_34->setObjectName("img_34");
        img_34->setGeometry(QRect(0, 0, 700, 410));
        img_34->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_9);
        img_34->raise();
        img_13->raise();
        push_13->raise();
        push_24->raise();
        sl_65->raise();
        sl_66->raise();
        sl_67->raise();
        sl_68->raise();
        sl_69->raise();
        sl_70->raise();
        sl_71->raise();
        text_29->raise();
        sl_72->raise();
        det_10 = new QWidget();
        det_10->setObjectName("det_10");
        img_30 = new QLabel(det_10);
        img_30->setObjectName("img_30");
        img_30->setGeometry(QRect(-30, 30, 490, 320));
        img_30->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img15.png")));
        img_30->setScaledContents(true);
        push_14 = new QCommandLinkButton(det_10);
        push_14->setObjectName("push_14");
        push_14->setGeometry(QRect(660, 180, 168, 41));
        push_14->setIcon(icon);
        push_25 = new QCommandLinkButton(det_10);
        push_25->setObjectName("push_25");
        push_25->setGeometry(QRect(10, 190, 31, 41));
        push_25->setIcon(icon1);
        sl_73 = new QCommandLinkButton(det_10);
        sl_73->setObjectName("sl_73");
        sl_73->setGeometry(QRect(430, 270, 168, 41));
        sl_74 = new QCommandLinkButton(det_10);
        sl_74->setObjectName("sl_74");
        sl_74->setGeometry(QRect(430, 300, 168, 41));
        sl_75 = new QCommandLinkButton(det_10);
        sl_75->setObjectName("sl_75");
        sl_75->setGeometry(QRect(430, 240, 168, 41));
        sl_76 = new QCommandLinkButton(det_10);
        sl_76->setObjectName("sl_76");
        sl_76->setGeometry(QRect(430, 150, 168, 41));
        sl_77 = new QCommandLinkButton(det_10);
        sl_77->setObjectName("sl_77");
        sl_77->setGeometry(QRect(430, 120, 168, 41));
        sl_78 = new QCommandLinkButton(det_10);
        sl_78->setObjectName("sl_78");
        sl_78->setGeometry(QRect(430, 210, 168, 41));
        sl_79 = new QCommandLinkButton(det_10);
        sl_79->setObjectName("sl_79");
        sl_79->setGeometry(QRect(430, 90, 168, 41));
        text_30 = new QLabel(det_10);
        text_30->setObjectName("text_30");
        text_30->setGeometry(QRect(440, 30, 141, 71));
        text_30->setFont(font4);
        text_30->setFocusPolicy(Qt::NoFocus);
        text_30->setAcceptDrops(false);
        text_30->setAutoFillBackground(false);
        text_30->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_30->setTextFormat(Qt::AutoText);
        text_30->setScaledContents(false);
        sl_80 = new QCommandLinkButton(det_10);
        sl_80->setObjectName("sl_80");
        sl_80->setGeometry(QRect(430, 180, 168, 41));
        img_35 = new QLabel(det_10);
        img_35->setObjectName("img_35");
        img_35->setGeometry(QRect(0, 0, 700, 410));
        img_35->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_10);
        img_35->raise();
        img_30->raise();
        push_14->raise();
        push_25->raise();
        sl_73->raise();
        sl_74->raise();
        sl_75->raise();
        sl_76->raise();
        sl_77->raise();
        sl_78->raise();
        sl_79->raise();
        text_30->raise();
        sl_80->raise();
        doctor_2 = new QWidget();
        doctor_2->setObjectName("doctor_2");
        img_20 = new QLabel(doctor_2);
        img_20->setObjectName("img_20");
        img_20->setGeometry(QRect(0, 0, 700, 400));
        img_20->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img2.jpg")));
        img_20->setScaledContents(true);
        doc = new QRadioButton(doctor_2);
        doc->setObjectName("doc");
        doc->setGeometry(QRect(280, 170, 201, 22));
        doc_7 = new QRadioButton(doctor_2);
        doc_7->setObjectName("doc_7");
        doc_7->setGeometry(QRect(280, 200, 161, 22));
        text_14 = new QLabel(doctor_2);
        text_14->setObjectName("text_14");
        text_14->setGeometry(QRect(270, 60, 191, 81));
        text_14->setFont(font2);
        text_14->setFocusPolicy(Qt::NoFocus);
        text_14->setAcceptDrops(false);
        text_14->setAutoFillBackground(false);
        text_14->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_14->setTextFormat(Qt::AutoText);
        text_14->setScaledContents(false);
        next_3 = new QPushButton(doctor_2);
        next_3->setObjectName("next_3");
        next_3->setGeometry(QRect(360, 330, 80, 24));
        next_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        back_8 = new QPushButton(doctor_2);
        back_8->setObjectName("back_8");
        back_8->setGeometry(QRect(270, 330, 80, 24));
        back_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(doctor_2);
        det_11 = new QWidget();
        det_11->setObjectName("det_11");
        img_21 = new QLabel(det_11);
        img_21->setObjectName("img_21");
        img_21->setGeometry(QRect(-30, 30, 490, 320));
        img_21->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img6.jpg")));
        img_21->setScaledContents(true);
        push_5 = new QCommandLinkButton(det_11);
        push_5->setObjectName("push_5");
        push_5->setGeometry(QRect(660, 180, 31, 41));
        push_5->setIcon(icon);
        push_26 = new QCommandLinkButton(det_11);
        push_26->setObjectName("push_26");
        push_26->setGeometry(QRect(10, 180, 31, 41));
        push_26->setIcon(icon1);
        sl_81 = new QCommandLinkButton(det_11);
        sl_81->setObjectName("sl_81");
        sl_81->setGeometry(QRect(430, 260, 168, 41));
        sl_82 = new QCommandLinkButton(det_11);
        sl_82->setObjectName("sl_82");
        sl_82->setGeometry(QRect(430, 290, 168, 41));
        sl_83 = new QCommandLinkButton(det_11);
        sl_83->setObjectName("sl_83");
        sl_83->setGeometry(QRect(430, 230, 168, 41));
        sl_84 = new QCommandLinkButton(det_11);
        sl_84->setObjectName("sl_84");
        sl_84->setGeometry(QRect(430, 140, 168, 41));
        sl_85 = new QCommandLinkButton(det_11);
        sl_85->setObjectName("sl_85");
        sl_85->setGeometry(QRect(430, 110, 168, 41));
        sl_86 = new QCommandLinkButton(det_11);
        sl_86->setObjectName("sl_86");
        sl_86->setGeometry(QRect(430, 200, 168, 41));
        sl_87 = new QCommandLinkButton(det_11);
        sl_87->setObjectName("sl_87");
        sl_87->setGeometry(QRect(430, 80, 168, 41));
        text_31 = new QLabel(det_11);
        text_31->setObjectName("text_31");
        text_31->setGeometry(QRect(440, 20, 141, 71));
        text_31->setFont(font4);
        text_31->setFocusPolicy(Qt::NoFocus);
        text_31->setAcceptDrops(false);
        text_31->setAutoFillBackground(false);
        text_31->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_31->setTextFormat(Qt::AutoText);
        text_31->setScaledContents(false);
        sl_88 = new QCommandLinkButton(det_11);
        sl_88->setObjectName("sl_88");
        sl_88->setGeometry(QRect(430, 170, 168, 41));
        img_36 = new QLabel(det_11);
        img_36->setObjectName("img_36");
        img_36->setGeometry(QRect(0, 0, 700, 410));
        img_36->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_11);
        img_36->raise();
        img_21->raise();
        push_5->raise();
        push_26->raise();
        sl_81->raise();
        sl_82->raise();
        sl_83->raise();
        sl_84->raise();
        sl_85->raise();
        sl_86->raise();
        sl_87->raise();
        text_31->raise();
        sl_88->raise();
        det_12 = new QWidget();
        det_12->setObjectName("det_12");
        img_22 = new QLabel(det_12);
        img_22->setObjectName("img_22");
        img_22->setGeometry(QRect(-30, 30, 490, 320));
        img_22->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img7.jpg")));
        img_22->setScaledContents(true);
        push_6 = new QCommandLinkButton(det_12);
        push_6->setObjectName("push_6");
        push_6->setGeometry(QRect(660, 180, 31, 41));
        push_6->setIcon(icon);
        push_27 = new QCommandLinkButton(det_12);
        push_27->setObjectName("push_27");
        push_27->setGeometry(QRect(10, 180, 31, 41));
        push_27->setIcon(icon1);
        sl_89 = new QCommandLinkButton(det_12);
        sl_89->setObjectName("sl_89");
        sl_89->setGeometry(QRect(430, 270, 168, 41));
        sl_90 = new QCommandLinkButton(det_12);
        sl_90->setObjectName("sl_90");
        sl_90->setGeometry(QRect(430, 300, 168, 41));
        sl_91 = new QCommandLinkButton(det_12);
        sl_91->setObjectName("sl_91");
        sl_91->setGeometry(QRect(430, 240, 168, 41));
        sl_92 = new QCommandLinkButton(det_12);
        sl_92->setObjectName("sl_92");
        sl_92->setGeometry(QRect(430, 150, 168, 41));
        sl_93 = new QCommandLinkButton(det_12);
        sl_93->setObjectName("sl_93");
        sl_93->setGeometry(QRect(430, 120, 168, 41));
        sl_94 = new QCommandLinkButton(det_12);
        sl_94->setObjectName("sl_94");
        sl_94->setGeometry(QRect(430, 210, 168, 41));
        sl_95 = new QCommandLinkButton(det_12);
        sl_95->setObjectName("sl_95");
        sl_95->setGeometry(QRect(430, 90, 168, 41));
        text_32 = new QLabel(det_12);
        text_32->setObjectName("text_32");
        text_32->setGeometry(QRect(440, 30, 141, 71));
        text_32->setFont(font4);
        text_32->setFocusPolicy(Qt::NoFocus);
        text_32->setAcceptDrops(false);
        text_32->setAutoFillBackground(false);
        text_32->setStyleSheet(QString::fromUtf8("color: rgb(48, 129, 178);\n"
""));
        text_32->setTextFormat(Qt::AutoText);
        text_32->setScaledContents(false);
        sl_96 = new QCommandLinkButton(det_12);
        sl_96->setObjectName("sl_96");
        sl_96->setGeometry(QRect(430, 180, 168, 41));
        img_37 = new QLabel(det_12);
        img_37->setObjectName("img_37");
        img_37->setGeometry(QRect(0, 0, 700, 410));
        img_37->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(det_12);
        img_37->raise();
        img_22->raise();
        push_6->raise();
        push_27->raise();
        sl_89->raise();
        sl_90->raise();
        sl_91->raise();
        sl_92->raise();
        sl_93->raise();
        sl_94->raise();
        sl_95->raise();
        text_32->raise();
        sl_96->raise();
        history = new QWidget();
        history->setObjectName("history");
        img_14 = new QLabel(history);
        img_14->setObjectName("img_14");
        img_14->setGeometry(QRect(-10, 0, 881, 410));
        img_14->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img3.jpg")));
        img_14->setScaledContents(true);
        text_19 = new QLabel(history);
        text_19->setObjectName("text_19");
        text_19->setGeometry(QRect(220, 20, 351, 81));
        QFont font5;
        font5.setFamilies({QString::fromUtf8("Bahnschrift SemiBold")});
        font5.setPointSize(28);
        font5.setBold(true);
        text_19->setFont(font5);
        text_19->setFocusPolicy(Qt::NoFocus);
        text_19->setAcceptDrops(false);
        text_19->setAutoFillBackground(false);
        text_19->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_19->setTextFormat(Qt::AutoText);
        text_19->setScaledContents(false);
        back_9 = new QPushButton(history);
        back_9->setObjectName("back_9");
        back_9->setGeometry(QRect(320, 350, 80, 24));
        back_9->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        tableView = new QTableView(history);
        tableView->setObjectName("tableView");
        tableView->setGeometry(QRect(5, 100, 691, 231));
        stackedWidget->addWidget(history);
        cancel = new QWidget();
        cancel->setObjectName("cancel");
        img_15 = new QLabel(cancel);
        img_15->setObjectName("img_15");
        img_15->setGeometry(QRect(0, 0, 700, 410));
        img_15->setPixmap(QPixmap(QString::fromUtf8("../Resourses/img3.jpg")));
        img_15->setScaledContents(true);
        text_20 = new QLabel(cancel);
        text_20->setObjectName("text_20");
        text_20->setGeometry(QRect(260, 20, 211, 81));
        text_20->setFont(font2);
        text_20->setFocusPolicy(Qt::NoFocus);
        text_20->setAcceptDrops(false);
        text_20->setAutoFillBackground(false);
        text_20->setStyleSheet(QString::fromUtf8("color: rgb(41, 48, 48);\n"
"color: rgb(0, 170, 255);"));
        text_20->setTextFormat(Qt::AutoText);
        text_20->setScaledContents(false);
        cancel_3 = new QPushButton(cancel);
        cancel_3->setObjectName("cancel_3");
        cancel_3->setGeometry(QRect(350, 300, 80, 24));
        cancel_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        c_doc = new QLineEdit(cancel);
        c_doc->setObjectName("c_doc");
        c_doc->setGeometry(QRect(210, 130, 321, 21));
        c_slot = new QLineEdit(cancel);
        c_slot->setObjectName("c_slot");
        c_slot->setGeometry(QRect(210, 170, 321, 21));
        c_pass = new QLineEdit(cancel);
        c_pass->setObjectName("c_pass");
        c_pass->setGeometry(QRect(210, 210, 321, 21));
        c_pass->setEchoMode(QLineEdit::Password);
        text_61 = new QLabel(cancel);
        text_61->setObjectName("text_61");
        text_61->setGeometry(QRect(100, 130, 91, 16));
        text_61->setMaximumSize(QSize(16777215, 16777215));
        text_61->setFont(font3);
        text_62 = new QLabel(cancel);
        text_62->setObjectName("text_62");
        text_62->setGeometry(QRect(100, 170, 91, 16));
        text_62->setMaximumSize(QSize(16777215, 16777215));
        text_62->setFont(font3);
        text_63 = new QLabel(cancel);
        text_63->setObjectName("text_63");
        text_63->setGeometry(QRect(100, 210, 101, 16));
        text_63->setMaximumSize(QSize(16777215, 16777215));
        text_63->setFont(font3);
        back_10 = new QPushButton(cancel);
        back_10->setObjectName("back_10");
        back_10->setGeometry(QRect(260, 300, 80, 24));
        back_10->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"));
        stackedWidget->addWidget(cancel);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(24);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        img->setText(QString());
        Sign->setText(QCoreApplication::translate("MainWindow", "Sign up", nullptr));
        text->setText(QCoreApplication::translate("MainWindow", "Don't have an account?", nullptr));
        Pass->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter password", nullptr));
        Title->setText(QCoreApplication::translate("MainWindow", "DOCTIME", nullptr));
        Login->setText(QCoreApplication::translate("MainWindow", "Log in", nullptr));
        Phone->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter phone number", nullptr));
        img_2->setText(QString());
        text_9->setText(QCoreApplication::translate("MainWindow", "SIGN UP", nullptr));
        Phone_4->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter your phone number", nullptr));
        Sign_4->setText(QCoreApplication::translate("MainWindow", "Sign up", nullptr));
        Pass_6->setPlaceholderText(QCoreApplication::translate("MainWindow", "Enter new password", nullptr));
        back_21->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_3->setText(QString());
        text_10->setText(QCoreApplication::translate("MainWindow", "MENU", nullptr));
        Logout_2->setText(QCoreApplication::translate("MainWindow", "Log out", nullptr));
        Cancel_2->setText(QCoreApplication::translate("MainWindow", "Cancel Appointment", nullptr));
        Book_2->setText(QCoreApplication::translate("MainWindow", "Book Appointment", nullptr));
        History_2->setText(QCoreApplication::translate("MainWindow", "Appointments", nullptr));
        img_4->setText(QString());
        sp_9->setText(QCoreApplication::translate("MainWindow", "Surgeon", nullptr));
        sp_10->setText(QCoreApplication::translate("MainWindow", "Psychiatrist", nullptr));
        text_11->setText(QCoreApplication::translate("MainWindow", "SPEACIALITY", nullptr));
        sp_4->setText(QCoreApplication::translate("MainWindow", "Neurologist", nullptr));
        sp_5->setText(QCoreApplication::translate("MainWindow", "Cardiologist", nullptr));
        sp_11->setText(QCoreApplication::translate("MainWindow", "General", nullptr));
        sp_12->setText(QCoreApplication::translate("MainWindow", "Dermalogist", nullptr));
        back->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_5->setText(QString());
        book_2->setText(QCoreApplication::translate("MainWindow", "Book", nullptr));
        text_12->setText(QCoreApplication::translate("MainWindow", "BOOK", nullptr));
        back_2->setText(QCoreApplication::translate("MainWindow", "Home", nullptr));
        pat_name->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter patient's name", nullptr));
        text_2->setText(QCoreApplication::translate("MainWindow", "Patient's name : ", nullptr));
        doc_name->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter doctor's name", nullptr));
        selected_slot->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter appoinment slot", nullptr));
        text_3->setText(QCoreApplication::translate("MainWindow", "Doctor's name : ", nullptr));
        text_4->setText(QCoreApplication::translate("MainWindow", "Selected slot    :", nullptr));
        text_5->setText(QCoreApplication::translate("MainWindow", "Patient's age    :", nullptr));
        patient_age->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter patient's age", nullptr));
        contact_no->setPlaceholderText(QCoreApplication::translate("MainWindow", "  Enter contact number", nullptr));
        text_59->setText(QCoreApplication::translate("MainWindow", "Contact no       :", nullptr));
        a_pass->setPlaceholderText(QCoreApplication::translate("MainWindow", "Confirm your password", nullptr));
        text_64->setText(QCoreApplication::translate("MainWindow", "Password          :", nullptr));
        img_6->setText(QString());
        text_13->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        doc_5->setText(QCoreApplication::translate("MainWindow", "Prof. Dr. M. Nazrul Islam", nullptr));
        next_2->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        doc_6->setText(QCoreApplication::translate("MainWindow", "Prof. Dr. Ashok Kumar Dutta", nullptr));
        back_3->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_7->setText(QString());
        push_3->setText(QString());
        push_16->setText(QString());
        img_16->setText(QString());
        text_21->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_2->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_3->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_5->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_6->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_7->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        sl_4->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        sl_8->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        img_8->setText(QString());
        push_4->setText(QString());
        push_17->setText(QString());
        img_17->setText(QString());
        sl_9->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_22->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_10->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        sl_11->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_12->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_13->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_14->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_15->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_16->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        img_9->setText(QString());
        doc_9->setText(QCoreApplication::translate("MainWindow", "Prof. Brig. Gen. Dr. Kumrul Hasan", nullptr));
        doc_10->setText(QCoreApplication::translate("MainWindow", "Dr. Md. Mahbub Hasan Bappi", nullptr));
        text_15->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        next_4->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        back_4->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_23->setText(QString());
        push_7->setText(QString());
        push_18->setText(QString());
        sl_17->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_18->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_19->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_20->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_21->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_22->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_23->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_23->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_24->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_18->setText(QString());
        img_24->setText(QString());
        push_8->setText(QString());
        push_19->setText(QString());
        sl_25->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_26->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_27->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_28->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_29->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_30->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_31->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_24->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_32->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_19->setText(QString());
        img_10->setText(QString());
        text_16->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        doc_11->setText(QCoreApplication::translate("MainWindow", "Dr. Asif Imran Siddiqui", nullptr));
        doc_12->setText(QCoreApplication::translate("MainWindow", "Prof. Lt. Col. Dr. Md. Abdul Wahab", nullptr));
        next_5->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        back_5->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_25->setText(QString());
        push_9->setText(QString());
        push_20->setText(QString());
        sl_33->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_34->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_35->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_36->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_37->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_38->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_39->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_25->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_40->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_29->setText(QString());
        img_26->setText(QString());
        push_10->setText(QString());
        push_21->setText(QString());
        sl_41->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_42->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_43->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_44->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_45->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_46->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_47->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_26->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_48->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_31->setText(QString());
        img_11->setText(QString());
        text_17->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        doc_13->setText(QCoreApplication::translate("MainWindow", "Lt. Col. Dr. Md. Nasir Uddin (Mahmud)", nullptr));
        doc_14->setText(QCoreApplication::translate("MainWindow", "Prof. Dr. A.H.M. Towhidul Alam", nullptr));
        next_6->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        back_6->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_27->setText(QString());
        push_11->setText(QString());
        push_22->setText(QString());
        sl_49->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_50->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_51->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_52->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_53->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_54->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_55->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_27->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_56->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_32->setText(QString());
        img_28->setText(QString());
        push_12->setText(QString());
        push_23->setText(QString());
        sl_57->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_58->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_59->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_60->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_61->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_62->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_63->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_28->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_64->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_33->setText(QString());
        img_12->setText(QString());
        text_18->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        doc_15->setText(QCoreApplication::translate("MainWindow", "Dr. Shamim Md. Fuad", nullptr));
        doc_16->setText(QCoreApplication::translate("MainWindow", "Prof. Dr. Syed Mozaffar Ahmed", nullptr));
        next_7->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        back_7->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_13->setText(QString());
        push_13->setText(QString());
        push_24->setText(QString());
        sl_65->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_66->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_67->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_68->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_69->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_70->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_71->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_29->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_72->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_34->setText(QString());
        img_30->setText(QString());
        push_14->setText(QString());
        push_25->setText(QString());
        sl_73->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_74->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_75->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_76->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_77->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_78->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_79->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_30->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_80->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_35->setText(QString());
        img_20->setText(QString());
        doc->setText(QCoreApplication::translate("MainWindow", "Dr. Md. Shuktarul Islam", nullptr));
        doc_7->setText(QCoreApplication::translate("MainWindow", "Prof. Dr. Anisul Haque", nullptr));
        text_14->setText(QCoreApplication::translate("MainWindow", "DOCTOR", nullptr));
        next_3->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        back_8->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        img_21->setText(QString());
        push_5->setText(QString());
        push_26->setText(QString());
        sl_81->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_82->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_83->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_84->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_85->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_86->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_87->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_31->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_88->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_36->setText(QString());
        img_22->setText(QString());
        push_6->setText(QString());
        push_27->setText(QString());
        sl_89->setText(QCoreApplication::translate("MainWindow", "8 : 30 PM", nullptr));
        sl_90->setText(QCoreApplication::translate("MainWindow", "8 : 45 PM", nullptr));
        sl_91->setText(QCoreApplication::translate("MainWindow", "8 : 15 PM", nullptr));
        sl_92->setText(QCoreApplication::translate("MainWindow", "7 : 30 PM", nullptr));
        sl_93->setText(QCoreApplication::translate("MainWindow", "7 : 15 PM", nullptr));
        sl_94->setText(QCoreApplication::translate("MainWindow", "8 : 00 PM", nullptr));
        sl_95->setText(QCoreApplication::translate("MainWindow", "7 : 00 PM", nullptr));
        text_32->setText(QCoreApplication::translate("MainWindow", "SLOTS", nullptr));
        sl_96->setText(QCoreApplication::translate("MainWindow", "7 : 45 PM", nullptr));
        img_37->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        img_14->setText(QString());
        text_19->setText(QCoreApplication::translate("MainWindow", "APPOINTMENTS", nullptr));
        back_9->setText(QCoreApplication::translate("MainWindow", "Home", nullptr));
        img_15->setText(QString());
        text_20->setText(QCoreApplication::translate("MainWindow", "CANCEL", nullptr));
        cancel_3->setText(QCoreApplication::translate("MainWindow", "Confirm", nullptr));
        c_doc->setPlaceholderText(QCoreApplication::translate("MainWindow", "Enter doctor's name", nullptr));
        c_slot->setPlaceholderText(QCoreApplication::translate("MainWindow", "Enter appointment slot", nullptr));
        c_pass->setPlaceholderText(QCoreApplication::translate("MainWindow", "Enter your password", nullptr));
        text_61->setText(QCoreApplication::translate("MainWindow", "Doctor's name : ", nullptr));
        text_62->setText(QCoreApplication::translate("MainWindow", "Selected slot    :", nullptr));
        text_63->setText(QCoreApplication::translate("MainWindow", "Password         :", nullptr));
        back_10->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
